services:
  - type: web
    name: bignay-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-vercel-frontend-url.vercel.app
